Repository lirantal/nodejs-cli-apps-best-practices, pull requests merged in 2020-04, with the labels that each got.

#47 WIP: feat(development): use relative paths
  README.md
Labels: enhancement

#49 docs(improvement): Update reference projects
  .gitignore
  README.md
Labels: documentation

#16 docs(distribution): New practice to cleanup configuration files
  README.md
Labels: new best practice

#52 docs(distribution): New practice to cleanup configuration files
  README_zh-CN.md
Labels: documentation

#53 docs: add m-sureshraj as a contributor
  README_zh-CN.md
Labels: documentation
