Repository lirantal/nodejs-cli-apps-best-practices, pull requests merged in 2020-02, with the labels that each got.

#1 [documentation, n/a] improved spelling and grammar
  README.md
Labels: documentation

#2 New practice: proper use of exit codes
  README.md
Labels: enhancement

#5 New practice: respect POSIX signals
  README.md
Labels: enhancement

#25 fix(accessibility): incorrect links use old name
  translations/zh/README.md
Labels: bug

#26 docs(accessibility): make recommendation clear
  translations/zh/README.md
Labels: enhancement

#22 docs(accessibility): make recommendation clear
  README.md
Labels: bug

#23 docs(accessibility): detect environment version
  README.md
Labels: enhancement

#4 New practice: a Development section with a new item
  README.md
Labels: documentation

#28 docs(layout): update badge data and langs info
  README.md
Labels: enhancement
